default: &default
  encoding: utf8
  host: localhost
  pool: 5
  adapter: mysql2

development:
  <<: *default
  database: <%= ENV['DATABASE_DEV_NAME'] %>
  username: <%= ENV['DATABASE_DEV_USER'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_DEV_NAME'] %>
  username: <%= ENV['DATABASE_DEV_USER'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>

production:
  <<: *default
  database: survey623_production
  username: root
  password:
